version: '3.1'

services:

  db:
    image: postgres:12-bullseye
    restart: always
    environment:
      POSTGRES_DB: "netology-db"
      POSTGRES_USER: "netology-db"
      POSTGRES_PASSWORD: "netology-db"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080